services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: autocheck-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env.docker
    ports:
      - "8484:8484"
    networks:
      - shared-postgres-network

networks:
  shared-postgres-network:
    external: true